# Generated by Django 4.2 on 2023-04-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0004_alter_quote_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
    ]
